---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: adservice
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'adservice:latest'
  source:
    contextDir: 'src/adservice/'
    git:
      ref: main
      uri: https://github.com/paulbarfuss/opentelemetry-demo
    type: Git
  strategy:
    type: Docker
  triggers:
    - type: ConfigChange
    - type: ImageChange
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: adservice
spec:
  lookupPolicy:
    local: true
