{{- range .Values.services }}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: "{{ service }}"
spec:
  output:
    to:
      kind: ImageStreamTag
      name: '{{ service }}:latest'
  source:
    contextDir: 'src/{{ service }}/src/'
    git:
      ref: "{{ .Values.git.ref }}"
      uri: "{{ .Values.git.uri }}"
    type: Git
  strategy:
    type: Docker
  triggers:
    - type: ConfigChange
    - type: ImageChange
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: "{{ service }}"
spec:
  lookupPolicy:
    local: true
{{- end }}