{{- $namespace := .Values.namespace }}
{{- $git_uri := .Values.git.uri }}
{{- $git_ref := .Values.git.ref }}
{{- range $service := .Values.services }}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: "{{ $service.name }}"
  namespace: "{{ $namespace }}"
spec:
  output:
    to:
      kind: ImageStreamTag
      name: "{{ $service.name }}:latest"
  source:
    contextDir: "{{ $service.contextdir | default "." }}"
    git:
      ref: "{{ $git_ref }}"
      uri: "{{ $git_uri }}"
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: "./src/{{ $service.name }}/{{ $service.dockerfile | default "Dockerfile" }}"
  triggers:
    - type: ConfigChange
    - type: ImageChange
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: "{{ $service.name }}"
  namespace: "{{ $namespace }}"
spec:
  lookupPolicy:
    local: true
{{- end }}